/**
 *
 * @author bengy
 */

package HilosForo;

import java.awt.Color;

public class Personas extends javax.swing.JFrame {

    int personas1;
    int personas2;
    int bol;
    

    Thread Entrada = new Thread() {

        public void run() {

            try {
                for (personas1 = 0; personas1 <= 500; personas1 += 20) {
                    jProgressBar1.setValue(personas1);
                    jProgressBar1.setMaximum(500);
                    entrada1.setText("Entradas vendidas: " + personas1);
                    Entrada.sleep(800);
                    jProgressBar1.setBackground(Color.BLUE);
                }

            } catch (Exception e) {

            }
        }

    };

    Thread Entrada2 = new Thread() {
         
        public void run() {
            try {       
                for (personas2 = 0; personas2 <= 500; personas2 += 20) {
                    
                    int disponibles = 1000 - (personas1+personas2);
                    
                    jProgressBar2.setValue(personas2);
                    jProgressBar2.setMaximum(500);
                    entrada2.setText("Entradas vendidas: " + personas2);
                    jLabel2.setText("Entradas disponibles: " + disponibles);
                    Entrada2.sleep(800);
                    jProgressBar2.setBackground(Color.RED);

                }

            } catch (Exception e) {

            }
        }

    };
    
    public Personas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        entrada1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        entrada2 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        entrada3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFocusable(false);
        jPanel1.setMinimumSize(new java.awt.Dimension(920, 400));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Puerta 2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 80, 20));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Puerta 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 80, 30));

        jButton1.setText("Vender boletos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 200, 50));

        entrada1.setBackground(new java.awt.Color(153, 153, 153));
        entrada1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        entrada1.setForeground(new java.awt.Color(255, 255, 255));
        entrada1.setText("...");
        entrada1.setOpaque(true);
        jPanel1.add(entrada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 200, -1));

        jProgressBar1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 660, 40));

        entrada2.setBackground(new java.awt.Color(153, 153, 153));
        entrada2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        entrada2.setForeground(new java.awt.Color(255, 255, 255));
        entrada2.setText("...");
        entrada2.setOpaque(true);
        jPanel1.add(entrada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 200, -1));

        jProgressBar2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 660, 40));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("...");
        jLabel2.setToolTipText("");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 210, 40));

        entrada3.setBackground(new java.awt.Color(0, 0, 0));
        entrada3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        entrada3.setForeground(new java.awt.Color(255, 255, 255));
        entrada3.setText("...");
        jPanel1.add(entrada3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Foro.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Entrada.start();
        Entrada2.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel entrada1;
    private javax.swing.JLabel entrada2;
    private javax.swing.JLabel entrada3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    // End of variables declaration//GEN-END:variables

}
